# Use postgres/password user/password credentials
version: '3.2'

services:

  app:
    build: .
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8080:8080
    environment:
      SECURITY.SQL_INJECTION: "False"
    command: ["./wait-for-it.sh", "db:5432", "--","java","-jar","-Dspring.profiles.active=docker","/opt/app.war"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      XVULB_DB_DATABASE: xvulb
      XVULB_DB_USER: xvulb_app
      XVULB_DB_PASSWORD: password
    ports:
      - 5432:5432
    build: 
      context: .
      dockerfile: Dockerfile.db
  
