# Use postgres/password user/password credentials
version: '3.2'

services:

  xvulb:
    build: .
    ports:
      - 8080:8080
    environment:
      SECURITY.SQL_INJECTION: "False"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      XVULB_DB_DATABASE: xvulb
      XVULB_DB_USER: xvulb_app
      XVULB_DB_PASSWORD: password
    ports:
      - 5432:5432
    build: 
      context: .
      dockerfile: Dockerfile.db
  
